import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapWrapper from "./BootstrapWrapper";
import '@fortawesome/fontawesome-free/css/all.min.css';
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          precedence="default"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapWrapper>
         
          <Header/>

          <main>{children}</main>

        <Footer/>
        </BootstrapWrapper>
      </body>
    </html>
  );
}
